<#
    Get-BuildDeps.ps1 -- fetch everything needed to compile the C++ part (copied from HeadTracking).

    The official UE4SSCPPTemplate cannot be used as-is: its CMakeLists does
    `add_subdirectory(RE-UE4SS)`, i.e. it builds UE4SS from source, which requires
    the private `deps/first/Unreal` submodule (Re-UE4SS/UEPseudo -- 404 anonymously,
    fetched in UE4SS CI with secrets.UEPSEUDO_PAT).

    We do not need it. Our mod never touches UObjects; that all stays in Lua. What
    we do need is:

      1. The PUBLIC part of RE-UE4SS, pinned to the exact commit the installed
         build came from, for its headers.
      2. fmt headers -- LuaMadeSimple.hpp includes <fmt/core.h>. It uses fmt exactly
         once, inside a template we never instantiate, so the header only has to
         parse.
      3. A trimmed copy of CppUserModBase.hpp.

    About (3): the real header includes <GUI/GUITab.hpp>, which pulls in GUI.hpp ->
    LiveView.hpp -> <Unreal/UFunctionStructs.hpp> from the private repo. GUITab is
    only needed as a complete type by `register_tab`, and Input types only by
    `register_keydown_event` -- both NON-VIRTUAL members we never call. Removing
    those two declarations and forward-declaring GUI::GUITab leaves the data members
    and, critically, the virtual function order untouched, so the vtable and object
    layout stay byte-identical to what UE4SS expects.

    The trim is done here programmatically from the pristine upstream header rather
    than by hand, so it stays faithful and is easy to re-audit.
#>

[CmdletBinding()]
param(
    # The commit the installed UE4SS build was produced from (see notes/progress.md).
    [string] $Ue4ssCommit = '1c1a1497f942c707f47ba668db75b25e86f6c08a',
    [string] $FmtTag      = '10.2.1'
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$third = Join-Path $repo 'third_party'
New-Item -ItemType Directory -Force -Path $third | Out-Null

# --------------------------------------------------------------- 1. RE-UE4SS
$ue4ssDir = Join-Path $third 'RE-UE4SS'
if (-not (Test-Path (Join-Path $ue4ssDir 'UE4SS\include\Mod\CppUserModBase.hpp'))) {
    Write-Host "Cloning public RE-UE4SS at $Ue4ssCommit ..." -ForegroundColor Cyan
    if (Test-Path $ue4ssDir) { Remove-Item $ue4ssDir -Recurse -Force }
    # No --recurse-submodules on purpose: the Unreal submodule is private and unneeded.
    git clone --filter=blob:none --no-checkout https://github.com/UE4SS-RE/RE-UE4SS.git $ue4ssDir
    Push-Location $ue4ssDir
    try {
        git checkout $Ue4ssCommit
    } finally { Pop-Location }
} else {
    Write-Host 'RE-UE4SS headers already present.' -ForegroundColor DarkGray
}

# ------------------------------------------------------------------- 2. fmt
$fmtDir = Join-Path $third 'fmt'
if (-not (Test-Path (Join-Path $fmtDir 'include\fmt\core.h'))) {
    Write-Host "Downloading fmt $FmtTag ..." -ForegroundColor Cyan
    $zip = Join-Path $env:TEMP "fmt-$FmtTag.zip"
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -UseBasicParsing `
        -Uri "https://github.com/fmtlib/fmt/archive/refs/tags/$FmtTag.zip" -OutFile $zip
    $tmp = Join-Path $env:TEMP "fmt-extract-$([guid]::NewGuid().ToString('N'))"
    Expand-Archive -Path $zip -DestinationPath $tmp -Force
    $src = Get-ChildItem $tmp -Directory | Select-Object -First 1
    New-Item -ItemType Directory -Force -Path $fmtDir | Out-Null
    Copy-Item (Join-Path $src.FullName 'include') $fmtDir -Recurse -Force
    Remove-Item $tmp -Recurse -Force
    Remove-Item $zip -Force
} else {
    Write-Host 'fmt headers already present.' -ForegroundColor DarkGray
}

# ------------------------------------------- 3. trimmed CppUserModBase.hpp
$shimDir = Join-Path $third 'shim\Mod'
New-Item -ItemType Directory -Force -Path $shimDir | Out-Null

$upstream = Join-Path $ue4ssDir 'UE4SS\include\Mod\CppUserModBase.hpp'
if (-not (Test-Path $upstream)) { throw "Upstream header missing: $upstream" }

$lines = Get-Content $upstream
$out = New-Object System.Collections.ArrayList
$removed = 0

[void]$out.Add('// GENERATED by scripts/Get-BuildDeps.ps1 -- do not edit by hand.')
[void]$out.Add('// Trimmed copy of UE4SS/include/Mod/CppUserModBase.hpp.')
[void]$out.Add('// Only two NON-VIRTUAL declarations are dropped (register_tab,')
[void]$out.Add('// register_keydown_event) plus the <GUI/GUITab.hpp> include, because that')
[void]$out.Add('// include chain reaches the private UEPseudo repository. Data members and')
[void]$out.Add('// virtual order are untouched, so layout and vtable match UE4SS exactly.')
[void]$out.Add('')

$skipping = $false
foreach ($line in $lines) {
    if ($line -match '^\s*#include\s*<GUI/GUITab\.hpp>') {
        [void]$out.Add('namespace RC::GUI { class GUITab; }  // was: #include <GUI/GUITab.hpp>')
        continue
    }
    if ($line -match '^\s*#include\s*<Input/Handler\.hpp>') {
        # Input/Handler.hpp is self-contained and public, but it is only needed by
        # the declarations we drop below, so leave it out too.
        [void]$out.Add('// removed: #include <Input/Handler.hpp> (only used by dropped declarations)')
        continue
    }
    if ($line -match 'RC_UE4SS_API auto register_tab' -or
        $line -match 'RC_UE4SS_API auto register_keydown_event') {
        $skipping = $true
        $removed++
    }
    if ($skipping) {
        # A declaration ends at the first line containing a semicolon.
        if ($line -match ';') { $skipping = $false }
        continue
    }
    [void]$out.Add($line)
}

$shimPath = Join-Path $shimDir 'CppUserModBase.hpp'
Set-Content -Path $shimPath -Value $out -Encoding UTF8
Write-Host ("Wrote trimmed header ({0} declarations dropped): {1}" -f $removed, $shimPath) -ForegroundColor Green

Write-Host ''
Write-Host 'Build dependencies ready.' -ForegroundColor Cyan
